create table applicant_data (
	id INT AUTO_INCREMENT PRIMARY KEY,
	first_name VARCHAR(255),
	last_name VARCHAR(255),
  nationality VARCHAR(255),
  age VARCHAR(10),
  gender VARCHAR(255),
	email VARCHAR(255),
	contact_no VARCHAR(50),
	home_address VARCHAR(255),
  position VARCHAR(255),
  location_pref VARCHAR(255),
	date_added TIMESTAMP 
);

insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (1, 'Dasie', 'Bramstom', 'Filipino', 37, 'Female', 'dbramstom0@digg.com', '+635378304375', 'Lot 14 Block 3 Barangay Tambo Parañaque City Metro Manila Philippines', 'Community Outreach', 'Borongan City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (2, 'Skippy', 'Capun', 'Filipino', 35, 'Male', 'scapun1@vk.com', '+636546256094', 'Lot 7 Block 12 Barangay Dolores Taytay Rizal Philippines', 'Community Outreach', 'Batangas City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (3, 'Dan', 'McGeown', 'Filipino', 38, 'Male', 'dmcgeown2@techcrunch.com', '+630392419531', 'Lot 13 Block 11 Barangay San Roque Antipolo City Rizal Philippines', 'Food Distribution', 'Zamboanga City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (4, 'Janelle', 'Holton', 'Filipino', 31, 'Female', 'jholton3@ucoz.com', '+636639229703', 'Lot 14 Block 3 Barangay Tambo Parañaque City Metro Manila Philippines', 'Community Outreach', 'Baybay City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (5, 'Meyer', 'Sprankling', 'Filipino', 26, 'Male', 'msprankling4@unicef.org', '+635269716303', 'Lot 18 Block 6 Barangay San Dionisio Parañaque City Metro Manila Philippines', 'Medical Support', 'Bacolod City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (6, 'Lennie', 'Carr', 'Filipino', 26, 'Male', 'lcarr5@bigcartel.com', '+630676196500', 'Lot 17 Block 12 Barangay San Agustin Dasmariñas Cavite Philippines', 'Shelter Management', 'Puerto Princesa City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (7, 'Franklyn', 'Briztman', 'Filipino', 19, 'Male', 'fbriztman6@cnbc.com', '+632894807292', 'Lot 21 Block 3 Barangay Magdalo Imus Cavite Philippines', 'Food Distribution', 'Tacloban City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (8, 'Serena', 'Enderwick', 'Filipino', 25, 'Female', 'senderwick7@4shared.com', '+638705754664', 'Lot 22 Block 11 Barangay Sto. Rosario Pateros Metro Manila Philippines', 'Shelter Management', 'Butuan City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (9, 'Wallace', 'Brunsdon', 'Filipino', 39, 'Genderfluid', 'wbrunsdon8@icio.us', '+632131023113', 'Lot 18 Block 6 Barangay San Dionisio Parañaque City Metro Manila Philippines', 'Logistics Coordination', 'Puerto Princesa City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (10, 'Nikolia', 'McGonigal', 'Filipino', 34, 'Female', 'nmcgonigal9@amazon.co.uk', '+635736872078', 'Lot 2 Block 13 Barangay Socorro Quezon City Metro Manila Philippines', 'Medical Support', 'Cebu City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (11, 'Krystalle', 'Kinnie', 'Filipino', 34, 'Female', 'kkinniea@dyndns.org', '+638203496057', 'Lot 18 Block 6 Barangay San Dionisio Parañaque City Metro Manila Philippines', 'Community Outreach', 'Manila');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (12, 'Hendrick', 'Cathesyed', 'Filipino', 24, 'Male', 'hcathesyedb@facebook.com', '+635037083771', 'Lot 12 Block 11 Barangay Rosario Pasig City Metro Manila Philippines', 'Food Distribution', 'Baguio City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (13, 'Coop', 'Irnis', 'Filipino', 24, 'Male', 'cirnisc@marketwatch.com', '+636634921463', 'Lot 21 Block 3 Barangay Magdalo Imus Cavite Philippines', 'Medical Support', 'Baguio City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (14, 'Coraline', 'Vahl', 'Filipino', 32, 'Female', 'cvahld@twitpic.com', '+635501379881', 'Lot 16 Block 9 Barangay Marulas Valenzuela City Metro Manila Philippines', 'Logistics Coordination', 'Dipolog City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (15, 'Chelsy', 'Bloomer', 'Filipino', 40, 'Female', 'cbloomere@apple.com', '+632100636831', 'Lot 6 Block 18 Barangay Talon Las Piñas City Metro Manila Philippines', 'Shelter Management', 'Zamboanga City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (16, 'Kimberli', 'Herkess', 'Filipino', 32, 'Female', 'kherkessf@spiegel.de', '+635077133817', 'Lot 9 Block 6 Barangay Santa Ana Manila Metro Manila Philippines', 'Shelter Management', 'Borongan City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (17, 'Ellswerth', 'California', 'Filipino', 32, 'Male', 'ecaliforniag@businesswire.com', '+631756218910', 'Lot 19 Block 10 Barangay Dalandanan Valenzuela City Metro Manila Philippines', 'Community Outreach', 'Laoag City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (18, 'Merilee', 'O''Hengerty', 'Filipino', 35, 'Female', 'mohengertyh@barnesandnoble.com', '+638430501145', 'Lot 22 Block 14 Barangay Bagong Ilog Pasig City Metro Manila Philippines', 'Medical Support', 'Olongapo City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (19, 'Bartholomeo', 'Quare', 'Filipino', 31, 'Polygender', 'bquarei@people.com.cn', '+632620810186', 'Lot 24 Block 9 Barangay San Juan Taytay Rizal Philippines', 'Shelter Management', 'Butuan City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (20, 'Alfie', 'Raincin', 'Filipino', 35, 'Agender', 'araincinj@edublogs.org', '+630795267347', 'Lot 6 Block 18 Barangay Talon Las Piñas City Metro Manila Philippines', 'Food Distribution', 'Marawi City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (21, 'Jacinda', 'Muzzi', 'Filipino', 25, 'Female', 'jmuzzik@oracle.com', '+636167074732', 'Lot 25 Block 7 Barangay Concepcion Marikina City Metro Manila Philippines', 'Medical Support', 'Naga City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (22, 'Karolina', 'L''Amie', 'Filipino', 29, 'Female', 'klamiel@comsenz.com', '+631887598690', 'Lot 6 Block 8 Barangay Santo Tomas Biñan City Laguna Philippines', 'Medical Support', 'Vigan City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (23, 'Dreddy', 'Hastings', 'Filipino', 36, 'Bigender', 'dhastingsm@prlog.org', '+634893216948', 'Lot 15 Block 5 Barangay BF Homes Parañaque City Metro Manila Philippines', 'Community Outreach', 'Manila');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (24, 'Lowe', 'Halt', 'Filipino', 24, 'Male', 'lhaltn@canalblog.com', '+638818238603', 'Lot 18 Block 6 Barangay Ugong Norte Quezon City Metro Manila Philippines', 'Food Distribution', 'Davao City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (25, 'Gay', 'Weakley', 'Filipino', 35, 'Female', 'gweakleyo@vinaora.com', '+636925870976', 'Lot 2 Block 13 Barangay Poblacion Calamba City Laguna Philippines', 'Medical Support', 'Cagayan de Oro City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (26, 'Juliette', 'Bassham', 'Filipino', 37, 'Female', 'jbasshamp@cyberchimps.com', '+637205367151', 'Lot 6 Block 8 Barangay Santo Tomas Biñan City Laguna Philippines', 'Shelter Management', 'Calbayog City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (27, 'Thaddus', 'Philbin', 'Filipino', 34, 'Male', 'tphilbinq@webnode.com', '+632179404797', 'Lot 7 Block 2 Barangay Cupang Antipolo City Rizal Philippines', 'Logistics Coordination', 'Olongapo City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (28, 'Roi', 'Santen', 'Filipino', 20, 'Male', 'rsantenr@wp.com', '+630936282672', 'Lot 2 Block 13 Barangay Poblacion Calamba City Laguna Philippines', 'Community Outreach', 'Lucena City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (29, 'Reinhard', 'Dacks', 'Filipino', 25, 'Male', 'rdackss@amazon.de', '+630711428957', 'Lot 11 Block 6 Barangay Bambang Taguig City Metro Manila Philippines', 'Medical Support', 'Iloilo City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (30, 'Marie-ann', 'Bransby', 'Filipino', 40, 'Female', 'mbransbyt@theatlantic.com', '+638357290519', 'Lot 15 Block 5 Barangay BF Homes Parañaque City Metro Manila Philippines', 'Community Outreach', 'Naga City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (31, 'Stevy', 'Nockells', 'Filipino', 36, 'Male', 'snockellsu@vimeo.com', '+636546849180', 'Lot 8 Block 15 Barangay Poblacion Makati City Metro Manila Philippines', 'Shelter Management', 'Zamboanga City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (32, 'Jemmy', 'Alliban', 'Filipino', 21, 'Female', 'jallibanv@xing.com', '+639696042086', 'Lot 10 Block 9 Barangay Pag-asa Quezon City Metro Manila Philippines', 'Shelter Management', 'Legazpi City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (33, 'Dorise', 'Gisbourn', 'Filipino', 35, 'Polygender', 'dgisbournw@newyorker.com', '+631169694214', 'Lot 14 Block 7 Barangay Salawag Dasmariñas Cavite Philippines', 'Shelter Management', 'Davao City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (34, 'Caprice', 'Wyre', 'Filipino', 22, 'Female', 'cwyrex@google.ca', '+638973667005', 'Lot 24 Block 9 Barangay San Juan Taytay Rizal Philippines', 'Food Distribution', 'Tuguegarao City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (35, 'Frans', 'O''Lynn', 'Filipino', 27, 'Male', 'folynny@privacy.gov.au', '+635846877004', 'Lot 4 Block 10 Barangay Bagumbayan Taguig City Metro Manila Philippines', 'Shelter Management', 'Borongan City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (36, 'Erina', 'Vivers', 'Filipino', 32, 'Female', 'eviversz@google.co.jp', '+630818137199', 'Lot 22 Block 14 Barangay Bagong Ilog Pasig City Metro Manila Philippines', 'Logistics Coordination', 'General Santos City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (37, 'Kelcey', 'Szwandt', 'Filipino', 23, 'Polygender', 'kszwandt10@163.com', '+631860899205', 'Lot 8 Block 10 Barangay Bagong Silang Caloocan City Metro Manila Philippines', 'Food Distribution', 'Borongan City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (38, 'Laurice', 'Oakenfull', 'Filipino', 31, 'Genderfluid', 'loakenfull11@instagram.com', '+630428053133', 'Lot 12 Block 11 Barangay Rosario Pasig City Metro Manila Philippines', 'Food Distribution', 'Bacolod City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (39, 'Glennis', 'Durdan', 'Filipino', 26, 'Female', 'gdurdan12@samsung.com', '+633605403853', 'Lot 5 Block 6 Barangay Kawit Cavite Philippines', 'Logistics Coordination', 'Tuguegarao City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (40, 'Pammy', 'Gossage', 'Filipino', 35, 'Female', 'pgossage13@si.edu', '+635540387581', '', 'Shelter Management', 'Tacloban City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (41, 'Constantine', 'Gledstane', 'Filipino', 18, 'Female', 'cgledstane14@miitbeian.gov.cn', '+635554075150', 'Lot 4 Block 10 Barangay Bagumbayan Taguig City Metro Manila Philippines', 'Food Distribution', 'Marawi City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (42, 'Roscoe', 'Hares', 'Filipino', 28, 'Male', 'rhares15@buzzfeed.com', '+638691804201', 'Lot 13 Block 11 Barangay San Roque Antipolo City Rizal Philippines', 'Food Distribution', 'Malaybalay City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (43, 'Hyman', 'Giannazzi', 'Filipino', 33, 'Male', 'hgiannazzi16@tumblr.com', '+634143886046', 'Lot 16 Block 9 Barangay Marulas Valenzuela City Metro Manila Philippines', 'Community Outreach', 'Naga City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (44, 'Glen', 'Andryunin', 'Filipino', 29, 'Male', 'gandryunin17@theatlantic.com', '+637580998158', 'Lot 12 Block 11 Barangay Rosario Pasig City Metro Manila Philippines', 'Logistics Coordination', 'Puerto Princesa City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (45, 'Augusto', 'Ratnege', 'Filipino', 24, 'Male', 'aratnege18@chicagotribune.com', '+631128649806', 'Lot 2 Block 13 Barangay Socorro Quezon City Metro Manila Philippines', 'Community Outreach', 'Manila');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (46, 'Maude', 'Livezley', 'Filipino', 37, 'Female', 'mlivezley19@abc.net.au', '+639599759656', 'Lot 18 Block 6 Barangay Ugong Norte Quezon City Metro Manila Philippines', 'Community Outreach', 'Cagayan de Oro City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (47, 'Hillard', 'Strattan', 'Filipino', 18, 'Male', 'hstrattan1a@jimdo.com', '+632005931058', 'Lot 18 Block 6 Barangay San Dionisio Parañaque City Metro Manila Philippines', 'Food Distribution', 'Marawi City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (48, 'Verne', 'Gilmour', 'Filipino', 27, 'Male', 'vgilmour1b@sina.com.cn', '+632651077399', 'Lot 17 Block 8 Barangay San Juan Cainta Rizal Philippines', 'Food Distribution', 'Borongan City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (49, 'Idalina', 'Rubartelli', 'Filipino', 30, 'Female', 'irubartelli1c@cpanel.net', '+636984349396', 'Lot 13 Block 2 Barangay Maybunga Pasig City Metro Manila Philippines', 'Community Outreach', 'General Santos City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (50, 'Meghann', 'Longlands', 'Filipino', 18, 'Female', 'mlonglands1d@infoseek.co.jp', '+631320953026', 'Lot 7 Block 2 Barangay Cupang Antipolo City Rizal Philippines', 'Medical Support', 'Bacolod City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (51, 'Denice', 'McVicar', 'Filipino', 36, 'Female', 'dmcvicar1e@economist.com', '+635083987747', 'Lot 22 Block 14 Barangay Bagong Ilog Pasig City Metro Manila Philippines', 'Shelter Management', 'Cagayan de Oro City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (52, 'Kaila', 'Loosmore', 'Filipino', 39, 'Female', 'kloosmore1f@nationalgeographic.com', '+631559047139', 'Lot 17 Block 12 Barangay San Agustin Dasmariñas Cavite Philippines', 'Community Outreach', 'Dipolog City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (53, 'Herc', 'Osinin', 'Filipino', 19, 'Male', 'hosinin1g@senate.gov', '+635163715817', 'Lot 8 Block 10 Barangay Bagong Silang Caloocan City Metro Manila Philippines', 'Community Outreach', 'Cebu City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (54, 'Abbot', 'Haitlie', 'Filipino', 22, 'Male', 'ahaitlie1h@4shared.com', '+634129772189', 'Lot 12 Block 7 Barangay Sampaloc Manila Metro Manila Philippines', 'Logistics Coordination', 'Dipolog City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (55, 'Cedric', 'Chessill', 'Filipino', 36, 'Agender', 'cchessill1i@cisco.com', '+638668889773', 'Lot 21 Block 3 Barangay Magdalo Imus Cavite Philippines', 'Food Distribution', 'Pagadian City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (56, 'Mersey', 'Hrachovec', 'Filipino', 37, 'Female', 'mhrachovec1j@cargocollective.com', '+633624442407', 'Lot 20 Block 2 Barangay Kapitolyo Pasig City Metro Manila Philippines', 'Food Distribution', 'Baguio City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (57, 'Annmaria', 'Geri', 'Filipino', 31, 'Female', 'ageri1k@latimes.com', '+634623341086', 'Lot 18 Block 6 Barangay Ugong Norte Quezon City Metro Manila Philippines', 'Community Outreach', 'Cebu City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (58, 'Dewie', 'Demetr', 'Filipino', 32, 'Male', 'ddemetr1l@opera.com', '+639099551194', 'Lot 8 Block 10 Barangay Bagong Silang Caloocan City Metro Manila Philippines', 'Medical Support', 'Legazpi City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (59, 'Cosmo', 'Bleackly', 'Filipino', 27, 'Genderqueer', 'cbleackly1m@cyberchimps.com', '+638924970848', 'Lot 7 Block 12 Barangay Dolores Taytay Rizal Philippines', 'Shelter Management', 'Calbayog City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (60, 'Magdalene', 'Dublin', 'Filipino', 26, 'Female', 'mdublin1n@g.co', '+631444148430', 'Lot 7 Block 12 Barangay Dolores Taytay Rizal Philippines', 'Shelter Management', 'Cebu City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (61, 'Happy', 'Philson', 'Filipino', 32, 'Female', 'hphilson1o@theatlantic.com', '+637363365890', 'Lot 12 Block 7 Barangay Sampaloc Manila Metro Manila Philippines', 'Medical Support', 'Butuan City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (62, 'Saw', 'Leaming', 'Filipino', 31, 'Male', 'sleaming1p@xing.com', '+631476478536', 'Lot 15 Block 3 Barangay Manggahan Pasig City Metro Manila Philippines', 'Food Distribution', 'Batangas City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (63, 'Shela', 'Rumsby', 'Filipino', 31, 'Female', 'srumsby1q@ning.com', '+636202277179', 'Lot 18 Block 6 Barangay San Dionisio Parañaque City Metro Manila Philippines', 'Shelter Management', 'Naga City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (64, 'Travers', 'MacInherney', 'Filipino', 23, 'Male', 'tmacinherney1r@economist.com', '+631383613305', 'Lot 8 Block 15 Barangay Poblacion Makati City Metro Manila Philippines', 'Shelter Management', 'Cebu City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (65, 'Scott', 'Whightman', 'Filipino', 27, 'Male', 'swhightman1s@storify.com', '+633369521986', 'Lot 10 Block 5 Barangay Molino IV Bacoor Cavite Philippines', 'Food Distribution', 'Naga City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (66, 'El', 'Chaplain', 'Filipino', 25, 'Male', 'echaplain1t@github.com', '+634046402549', 'Lot 25 Block 7 Barangay Concepcion Marikina City Metro Manila Philippines', 'Community Outreach', 'Bacolod City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (67, 'Gustaf', 'Cubbit', 'Filipino', 18, 'Male', 'gcubbit1u@economist.com', '+636145416298', 'Lot 2 Block 13 Barangay Socorro Quezon City Metro Manila Philippines', 'Logistics Coordination', 'Calbayog City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (68, 'Britni', 'Corn', 'Filipino', 27, 'Female', 'bcorn1v@addthis.com', '+635458125192', 'Lot 13 Block 11 Barangay San Roque Antipolo City Rizal Philippines', 'Shelter Management', 'Malaybalay City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (69, 'Jesus', 'Hallt', 'Filipino', 28, 'Male', 'jhallt1w@slate.com', '+633871858968', 'Lot 17 Block 8 Barangay San Juan Cainta Rizal Philippines', 'Community Outreach', 'Cebu City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (70, 'Hedvig', 'McBeth', 'Filipino', 18, 'Female', 'hmcbeth1x@sitemeter.com', '+634176688737', 'Lot 5 Block 9 Barangay San Miguel Quezon City Metro Manila Philippines', 'Medical Support', 'Olongapo City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (71, 'Jacinda', 'Chevolleau', 'Filipino', 31, 'Female', 'jchevolleau1y@cisco.com', '+637868104486', 'Lot 13 Block 2 Barangay Maybunga Pasig City Metro Manila Philippines', 'Shelter Management', 'Iloilo City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (72, 'Zacharia', 'Jones', 'Filipino', 29, 'Male', 'zjones1z@wsj.com', '+632035789023', 'Lot 22 Block 11 Barangay Sto. Rosario Pateros Metro Manila Philippines', 'Shelter Management', 'Legazpi City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (73, 'Bren', 'Darte', 'Filipino', 39, 'Male', 'bdarte20@wired.com', '+636201642409', 'Lot 16 Block 9 Barangay Marulas Valenzuela City Metro Manila Philippines', 'Logistics Coordination', 'Baguio City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (74, 'Scarface', 'Medlar', 'Filipino', 40, 'Male', 'smedlar21@tumblr.com', '+631721586343', 'Lot 15 Block 3 Barangay Manggahan Pasig City Metro Manila Philippines', 'Food Distribution', 'Bacolod City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (75, 'Annabela', 'McGiffie', 'Filipino', 25, 'Female', 'amcgiffie22@msu.edu', '+637669939812', 'Lot 4 Block 12 Barangay San Andres Malate Manila Metro Manila Philippines', 'Community Outreach', 'Naga City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (76, 'Gualterio', 'Esterbrook', 'Filipino', 21, 'Male', 'gesterbrook23@techcrunch.com', '+639897435846', 'Lot 12 Block 11 Barangay Rosario Pasig City Metro Manila Philippines', 'Food Distribution', 'Lucena City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (77, 'Annmarie', 'Danielli', 'Filipino', 21, 'Female', 'adanielli24@unesco.org', '+637309117495', 'Lot 13 Block 2 Barangay Maybunga Pasig City Metro Manila Philippines', 'Community Outreach', 'Baguio City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (78, 'Alexina', 'Morgans', 'Filipino', 21, 'Female', 'amorgans25@ucla.edu', '+630958215676', 'Lot 9 Block 5 Barangay San Isidro Taytay Rizal Philippines', 'Food Distribution', 'Angeles City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (79, 'Quentin', 'Codrington', 'Filipino', 24, 'Male', 'qcodrington26@163.com', '+639294954764', 'Lot 22 Block 11 Barangay Sto. Rosario Pateros Metro Manila Philippines', 'Community Outreach', 'Vigan City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (80, 'Seana', 'Pitrelli', 'Filipino', 35, 'Genderfluid', 'spitrelli27@loc.gov', '+634615020263', 'Lot 10 Block 5 Barangay Molino IV Bacoor Cavite Philippines', 'Medical Support', 'Iloilo City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (81, 'Arabela', 'Palffy', 'Filipino', 36, 'Female', 'apalffy28@tumblr.com', '+634683800187', 'Lot 18 Block 6 Barangay Ugong Norte Quezon City Metro Manila Philippines', 'Food Distribution', 'Baguio City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (82, 'Zelig', 'Penwright', 'Filipino', 25, 'Male', 'zpenwright29@reference.com', '+636261321848', 'Lot 12 Block 7 Barangay Sampaloc Manila Metro Manila Philippines', 'Medical Support', 'Baybay City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (83, 'Ernesta', 'Gooderridge', 'Filipino', 25, 'Female', 'egooderridge2a@theatlantic.com', '+631533301081', '', 'Logistics Coordination', 'Cotabato City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (84, 'Cob', 'Goodenough', 'Filipino', 35, 'Male', 'cgoodenough2b@github.io', '+631019112012', 'Lot 20 Block 2 Barangay Kapitolyo Pasig City Metro Manila Philippines', 'Medical Support', 'Laoag City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (85, 'Hastie', 'Gothrup', 'Filipino', 21, 'Male', 'hgothrup2c@wiley.com', '+630216662273', 'Lot 7 Block 12 Barangay Dolores Taytay Rizal Philippines', 'Community Outreach', 'Bacolod City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (86, 'Lowell', 'Brettoner', 'Filipino', 40, 'Non-binary', 'lbrettoner2d@godaddy.com', '+630472601546', 'Lot 21 Block 9 Barangay Santo Niño Marikina City Metro Manila Philippines', 'Food Distribution', 'Lucena City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (87, 'Morgana', 'Whitters', 'Filipino', 23, 'Female', 'mwhitters2e@gmpg.org', '+631501682023', 'Lot 6 Block 8 Barangay Santo Tomas Biñan City Laguna Philippines', 'Community Outreach', 'Davao City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (88, 'Tan', 'Critcher', 'Filipino', 18, 'Polygender', 'tcritcher2f@ocn.ne.jp', '+631236794780', 'Lot 11 Block 1 Barangay San Vicente San Pedro Laguna Philippines', 'Shelter Management', 'Marawi City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (89, 'Rich', 'Agus', 'Filipino', 21, 'Male', 'ragus2g@paginegialle.it', '+631923961740', 'Lot 4 Block 10 Barangay Bagumbayan Taguig City Metro Manila Philippines', 'Medical Support', 'Batangas City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (90, 'Carrol', 'Dahler', 'Filipino', 27, 'Male', 'cdahler2h@simplemachines.org', '+632158221837', 'Lot 9 Block 6 Barangay Santa Ana Manila Metro Manila Philippines', 'Food Distribution', 'Dipolog City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (91, 'Tyrone', 'D''Hooghe', 'Filipino', 31, 'Male', 'tdhooghe2i@mtv.com', '+630820523020', 'Lot 9 Block 5 Barangay San Isidro Taytay Rizal Philippines', 'Community Outreach', 'Baguio City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (92, 'Nonie', 'Hastwell', 'Filipino', 28, 'Female', 'nhastwell2j@ask.com', '+636702406762', 'Lot 17 Block 8 Barangay San Juan Cainta Rizal Philippines', 'Shelter Management', 'Baguio City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (93, 'Ketty', 'Moir', 'Filipino', 31, 'Female', 'kmoir2k@statcounter.com', '+636010167283', 'Lot 20 Block 4 Barangay San Pedro Laguna Philippines', 'Logistics Coordination', 'Cagayan de Oro City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (94, 'Gabi', 'Barwise', 'Filipino', 32, 'Polygender', 'gbarwise2l@icq.com', '+631216931184', 'Lot 10 Block 5 Barangay Molino IV Bacoor Cavite Philippines', 'Shelter Management', 'Laoag City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (95, 'Brita', 'Labat', 'Filipino', 39, 'Female', 'blabat2m@unesco.org', '+639215531174', 'Lot 8 Block 2 Barangay Barangka Mandaluyong City Metro Manila Philippines', 'Community Outreach', 'Davao City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (96, 'Leeland', 'Ranklin', 'Filipino', 35, 'Male', 'lranklin2n@hostgator.com', '+637204699031', 'Lot 2 Block 13 Barangay Poblacion Calamba City Laguna Philippines', 'Community Outreach', 'General Santos City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (97, 'Dieter', 'Milley', 'Filipino', 22, 'Male', 'dmilley2o@instagram.com', '+631956226316', 'Lot 4 Block 10 Barangay Bagumbayan Taguig City Metro Manila Philippines', 'Logistics Coordination', 'Angeles City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (98, 'Cicely', 'Rubert', 'Filipino', 36, 'Female', 'crubert2p@ow.ly', '+630296930453', 'Lot 22 Block 14 Barangay Bagong Ilog Pasig City Metro Manila Philippines', 'Food Distribution', 'Olongapo City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (99, 'Constance', 'Pfeifer', 'Filipino', 18, 'Female', 'cpfeifer2q@mtv.com', '+638008321818', 'Lot 14 Block 3 Barangay Tambo Parañaque City Metro Manila Philippines', 'Shelter Management', 'Baguio City');
insert into applicant_data (id, first_name, last_name, nationality, age, gender, email, contact_no, home_address, position, location_pref) values (100, 'Thornie', 'Camblin', 'Filipino', 36, 'Male', 'tcamblin2r@printfriendly.com', '+637671139256', 'Lot 18 Block 6 Barangay San Dionisio Parañaque City Metro Manila Philippines', 'Medical Support', 'Pagadian City');